spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.healthcheck.enabled=true
eureka.instance.instance-id=${spring.application.name}:${server.port}


jwt.public-key=${JWT_PUBLIC_KEY}

gateway.internal-secret=${GATEWAY_SECRET}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always
management.endpoint.gateway.enabled=true

logging.level.ba.etf.fixit.apigateway=DEBUG
logging.level.org.springframework.cloud.gateway=INFO

spring.main.web-application-type=reactive
# Multipart podrska - potrebno za upload fotografija kroz gateway
spring.codec.max-in-memory-size=26MB
spring.cloud.gateway.httpclient.max-header-size=65536