spring.application.name=management-service
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/fixit_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Hibernate statistics za N+1 provjeru
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.healthcheck.enabled=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

discovery.user-service.direct-base-url=http://localhost:8081

# Gateway secret — mora biti isti kao u api-gateway
gateway.internal-secret=${GATEWAY_SECRET}

# Direktni URL za report-service 
discovery.report-service.direct-base-url=http://localhost:8083
